### ISSUE TITLE
Can't the language change be done without the document reload?

### ISSUE THREAD

**Issue by thistehneisen** [Lablnet/Javascript-Language-Selector#1]
Otherwise it's defeating one of the core purposes for choosing a JS language switcher.

**Comment by thistehneisen** [comment]
Now I understand why you put the location reload there, as it's breaking any other jQuery functionality by replacing the HTML… so basically it should be placed before ANY other jQuery scripts.

**Comment by lablnet** [comment]
> Now I understand why you put the location reload there, as it's breaking any other jQuery functionality by replacing the HTML… so basically it should be placed before ANY other jQuery scripts.


Yes, i will update to make it reactive.

**Comment by thistehneisen** [comment]
I did make a pull request that works perfectly fine until the replaceable string contains HTML. Currently seems like I'll just have to switch back to server-side.

**Comment by lablnet** [comment]
> I did make a pull request that works perfectly fine until the replaceable string contains HTML. Currently seems like I'll just have to switch back to server-side.

U can sent PR we will discuss  it to improve
